# Generated by Django 5.0.6 on 2024-07-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticia', models.CharField(max_length=100)),
                ('portada', models.ImageField(null=True, upload_to='productos')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
