# Generated by Django 5.0.6 on 2024-07-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_noticias_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='descrip',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
