# Generated by Django 5.0.6 on 2024-07-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_noticias_descrip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galerias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galeria', models.ImageField(null=True, upload_to='galeria')),
            ],
        ),
    ]
