# Generated by Django 5.0.6 on 2024-07-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_galerias'),
    ]

    operations = [
        migrations.AddField(
            model_name='galerias',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
